In [2]:
import pandas as pd

In [3]:
movies = pd.read_csv('https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/imdb_1000.csv')
movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

### Filtrar con un condicional y una variable

In [4]:
# Para filtrar con un condicional, creamos una variable de filtro
filtro = (movies['duration'] >= 150)

In [5]:
movies[filtro]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
...,...,...,...,...,...,...
909,7.5,Harry Potter and the Sorcerer's Stone,PG,Adventure,152,"[u'Daniel Radcliffe', u'Rupert Grint', u'Richa..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."

### Aplicar un filtro directo al data frame - df[(df[â€˜columnaâ€™] condicion)]

In [6]:
# Para hacerlo, creamos el filtro y lo aplicamos directo al data frame df[(filtro)]
movies[(movies['duration'] >= 150)]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
...,...,...,...,...,...,...
909,7.5,Harry Potter and the Sorcerer's Stone,PG,Adventure,152,"[u'Daniel Radcliffe', u'Rupert Grint', u'Richa..."
941,7.4,A Bridge Too Far,PG,Drama,175,"[u'Sean Connery', u""Ryan O'Neal"", u'Michael Ca..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."

### Filtrar con .loc y dos o mas variables

In [7]:
# Filtrar con .loc y dos o mas variables
movies.loc[filtro, ['title','star_rating','duration']].sort_values(by='star_rating', 
                                                                   ascending = False).head(20)

                                                title  star_rating  duration
1                                       The Godfather          9.2       175
2                              The Godfather: Part II          9.1       200
3                                     The Dark Knight          9.0       152
4                                        Pulp Fiction          8.9       154
6                      The Good, the Bad and the Ugly          8.9       161
7       The Lord of the Rings: The Return of the King          8.9       201
8                                    Schindler's List          8.9       195
10  The Lord of the Rings: The Fellowship of the Ring          8.8       178
14              The Lord of the Rings: The Two Towers          8.8       179
17                                      Seven Samurai          8.7       207
15                                       Interstellar          8.7       169
26                       Once Upon a Time in the West          8.6       175
36                                Saving Private Ryan          8.6       169
49                                       The Departed          8.5       151
60                                           3 Idiots          8.5       170
59                                   Django Unchained          8.5       165
51                                     Apocalypse Now          8.5       153
50                                    Cinema Paradiso          8.5       155
40                                     The Green Mile          8.5       189
47                                   Taare Zameen Par          8.5       165

### Aplicar filtros dobles - Dos condiciones & u |

In [8]:
filtro = (movies['duration'] >= 180) & (movies['genre'] == 'Drama')

In [9]:
movies[(movies['duration'] >= 180) & (movies['genre'] == 'Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."
318,8.0,Magnolia,R,Drama,188,"[u'Tom Cruise', u'Jason Robards', u'Julianne M..."
335,8.0,Doctor Zhivago,PG-13,Drama,197,"[u'Omar Sharif', u'Julie Christie', u'Geraldin..."
361,8.0,Fiddler on the Roof,G,Drama,181,"[u'Topol', u'Norma Crane', u'Leonard Frey']"
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."

In [10]:
movies[(movies['duration'] >= 180) | (movies['genre'] == 'Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
9,8.9,Fight Club,R,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."
...,...,...,...,...,...,...
958,7.4,My Sister's Keeper,PG-13,Drama,109,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B..."
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."

### Filtrar multiples condiciones de OR con isin()

In [11]:
# Creamos las condiciones del filtro, pero dentro de la funcion isin()
movies[(movies['genre'].isin(['Crime', 'Drama', 'Adventure']))]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
...,...,...,...,...,...,...
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [12]:
import numpy as np

In [13]:
movies.select_dtypes(include=object).dtypes

title             object
content_rating    object
genre             object
actors_list       object
dtype: object

In [14]:
movies.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [ ]:
#query() allows Boolean expressions for filtering rows.
#df.query('Length > 7')
#df.query('Length > 7 and Width < 8')
#df.query('Name.str.startswith("abc")', 
#engine="python")

In [15]:
movies.head(5)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [20]:
movies.query('duration > 200').sort_values(by='star_rating', ascending = False)

,star_rating,title,content_rating,genre,duration,actors_list
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."